### ISSUE TITLE
Better exception highlight in tracebacks

### ISSUE THREAD

**Issue by nicoddemus** [nicoddemus/pytest-rich#5]
pytest doesn't provide the actual traceback objects during report (this is due to xdist support, because the report objects need to be serialized to be transferred between processes), we currently we only show the text with some simple highlighting.

See if we can leverage rich's traceback highlighting somehow.

**Comment by joshuadavidthomas** [comment]
Dug in to this a bit last night.

To assemble the `Traceback`, Rich walks through the actual traceback:

https://github.com/Textualize/rich/blob/8c3e6be424f36522cbb3c4773e58a01f5f39761f/rich/traceback.py#L364-L384

Since we don't have access to the traceback, just pytest's serialized `TestReport`, I don't immediately see a way to utilize Rich's actual `Traceback` class.

The easy path I see is, instead of dumping the `report.longrepr` to markdown, creating a Rich `Panel` and assembling a console printout using the `ExceptionChainRepr` info from `longrepr` that at least *resembles* the printout from Rich's `Traceback`.

**Comment by nicoddemus** [comment]
Thanks for looking into it.

Yeah that seems like a possible solution.

Another solution that comes to mind is borrowing the code from rich that prints a `Traceback` and copy/change it to work with the contents of `ExceptionChainRepr` instead.

**Comment by nicoddemus** [comment]
Not sure, but my suggestion is a bit different: search in Rich's codebase for the code that prints `Traceback` objects, then copy it over and adapt it to print `ExceptionChainRepr` instead.
